version: '3'
services:
  db:
    image: postgres:latest
    hostname: db
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
      POSTGRES_DB: ${SQL_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data


  app:
    build: .
    command: sh -c "sleep 30 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    hostname: app
    ports:
      - 8000:8000
    env_file:
      - ./.env
    volumes:
      - .:/app
    depends_on:
      - db


volumes:
  postgres_data:
